// DO NOT EDIT. generated by webtyp.com/ormc

package contact

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Contact struct {
	Id int64
	Nombre string
	Email string
	Mensaje string
}

func (m *Contact) ModelName() string { return "contact" }

func (m *Contact) Schema() []model.Field { return ContactModel.Fields }

func (m *Contact) Pointers() []any { return []any{&m.Id, &m.Nombre, &m.Email, &m.Mensaje} }

func (m *Contact) IsNil() bool { return m == nil }

func (m *Contact) EncodeFields(w model.FieldWriter) {
	w.Int("id", m.Id)
	w.String("nombre", m.Nombre)
	w.String("email", m.Email)
	w.String("mensaje", m.Mensaje)
}

func (m *Contact) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("id"); ok { m.Id = v }
	if v, ok := r.String("nombre"); ok { m.Nombre = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("mensaje"); ok { m.Mensaje = v }
}

type ContactList []*Contact

func (s *ContactList) Len() int             { return len(*s) }
func (s *ContactList) At(i int) model.Fielder { return (*s)[i] }
func (s *ContactList) Append() model.Fielder  { v := &Contact{}; *s = append(*s, v); return v }
func (s *ContactList) IsNil() bool          { return s == nil }
func (s *ContactList) EncodeFields(_ model.FieldWriter) {}
func (s *ContactList) DecodeFields(_ model.FieldReader) {}

func (m *Contact) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Contact_ = struct {
	Id string
	Nombre string
	Email string
	Mensaje string
}{
	Id: "id",
	Nombre: "nombre",
	Email: "email",
	Mensaje: "mensaje",
}

func ReadOneContact(qb *orm.QB, model *Contact) (*Contact, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllContact(qb *orm.QB) (ContactList, error) {
	var results ContactList
	err := qb.ReadAll(
		func() model.Model { return &Contact{} },
		func(m model.Model) { results = append(results, m.(*Contact)) },
	)
	return results, err
}

type EmailPayload struct {
	From string
	To string
	Subject string
	Html string
}

func (m *EmailPayload) ModelName() string { return "email_payload" }

func (m *EmailPayload) Schema() []model.Field { return EmailPayloadModel.Fields }

func (m *EmailPayload) Pointers() []any { return []any{&m.From, &m.To, &m.Subject, &m.Html} }

func (m *EmailPayload) IsNil() bool { return m == nil }

func (m *EmailPayload) EncodeFields(w model.FieldWriter) {
	w.String("from", m.From)
	w.String("to", m.To)
	w.String("subject", m.Subject)
	w.Raw("html", m.Html)
}

func (m *EmailPayload) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("from"); ok { m.From = v }
	if v, ok := r.String("to"); ok { m.To = v }
	if v, ok := r.String("subject"); ok { m.Subject = v }
	if v, ok := r.Raw("html"); ok { m.Html = v }
}

type EmailPayloadList []*EmailPayload

func (s *EmailPayloadList) Len() int             { return len(*s) }
func (s *EmailPayloadList) At(i int) model.Fielder { return (*s)[i] }
func (s *EmailPayloadList) Append() model.Fielder  { v := &EmailPayload{}; *s = append(*s, v); return v }
func (s *EmailPayloadList) IsNil() bool          { return s == nil }
func (s *EmailPayloadList) EncodeFields(_ model.FieldWriter) {}
func (s *EmailPayloadList) DecodeFields(_ model.FieldReader) {}

func (m *EmailPayload) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

